spring:
  application:
    name: "consumer-service"
  kafka:
    consumer:
      client-id: "consumer-service"
      auto-offset-reset: latest
      group-id: "metrics-group"
    bootstrap-servers: "localhost:29092"
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:./db/consumer-h2-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;"
    username: "sa"
    password: "sa"
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: off
  port: 8081
consumer-service:
  kafka:
    topic: "metrics-topic"